# Generated by Django 4.2 on 2024-07-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='age',
        ),
        migrations.AddField(
            model_name='farmer',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
