# Generated by Django 4.2 on 2024-07-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_farmer_age_farmer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='user_id',
            new_name='user',
        ),
    ]
